import type { Application, Job } from "./types";

export const jobs: Job[] = [
  {
    slug: "senior-fullstack-engineer-nimbus",
    title: "Senior Full Stack Engineer",
    company: "Nimbus Labs",
    companyInitials: "NL",
    companyAccent: "from-emerald-500/30 to-emerald-400/10",
    location: "Sydney, NSW",
    workstyle: "Hybrid",
    employment: "Full-time",
    seniority: "Senior",
    salaryMin: 160000,
    salaryMax: 195000,
    postedAt: "2026-05-09T08:30:00Z",
    applicants: 38,
    category: "Engineering",
    description:
      "Lead the build of our next-generation rewards platform with a small product-engineering team. You'll own architecture decisions across the Next.js front end, Node/TypeScript services, and our Postgres data layer.",
    responsibilities: [
      "Design and ship full-stack features in Next.js, TypeScript, and Postgres",
      "Mentor mid-level engineers through code review and pairing",
      "Partner with product on roadmap shaping",
      "Own observability and performance budgets",
    ],
    requirements: [
      "5+ years building production web applications",
      "Strong TypeScript + React fundamentals",
      "Postgres / Prisma comfort",
      "AU work rights",
    ],
    perks: [
      "Hybrid (Sydney HQ Tue/Thu)",
      "Stock options",
      "Generous learning budget",
      "Two engineering retreats / year",
    ],
  },
  {
    slug: "product-designer-rivermark",
    title: "Senior Product Designer",
    company: "Rivermark",
    companyInitials: "RM",
    companyAccent: "from-rose-500/30 to-rose-400/10",
    location: "Melbourne, VIC",
    workstyle: "Remote",
    employment: "Full-time",
    seniority: "Senior",
    salaryMin: 145000,
    salaryMax: 175000,
    postedAt: "2026-05-10T11:00:00Z",
    applicants: 27,
    category: "Design",
    description:
      "Own the end-to-end design of our merchant onboarding and dashboard surfaces. Work directly with the founding team to set the bar on craft.",
    responsibilities: [
      "Lead discovery, interaction, and visual design",
      "Build and maintain the design system in Figma",
      "Pair with engineers through implementation",
      "Run weekly design critiques",
    ],
    requirements: [
      "5+ years of product design experience",
      "Strong portfolio of shipped B2B SaaS",
      "Comfortable in Figma + handoff workflows",
    ],
    perks: ["Fully remote (AU-based)", "Stock options", "Home office allowance"],
  },
  {
    slug: "data-engineer-pivotal",
    title: "Data Engineer",
    company: "Pivotal Health",
    companyInitials: "PH",
    companyAccent: "from-cyan-500/30 to-cyan-400/10",
    location: "Brisbane, QLD",
    workstyle: "Hybrid",
    employment: "Full-time",
    seniority: "Mid",
    salaryMin: 130000,
    salaryMax: 155000,
    postedAt: "2026-05-08T15:20:00Z",
    applicants: 19,
    category: "Data",
    description:
      "Build the pipelines that power our clinical analytics. You'll own ingestion, transformation, and serving for a fast-growing health platform.",
    responsibilities: [
      "Design and operate ELT pipelines in dbt + Snowflake",
      "Work with clinicians to model the right outcomes",
      "Own data quality and SLAs",
    ],
    requirements: [
      "3+ years in a data engineering role",
      "Strong SQL + Python",
      "dbt experience preferred",
    ],
    perks: ["Hybrid (Brisbane)", "Annual healthcare allowance"],
  },
  {
    slug: "frontend-engineer-loop",
    title: "Frontend Engineer",
    company: "Loopline",
    companyInitials: "LL",
    companyAccent: "from-amber-500/30 to-amber-400/10",
    location: "Remote (AU)",
    workstyle: "Remote",
    employment: "Full-time",
    seniority: "Mid",
    salaryMin: 125000,
    salaryMax: 150000,
    postedAt: "2026-05-11T05:00:00Z",
    applicants: 12,
    category: "Engineering",
    description:
      "Help ship the public-facing experience of our subscription platform. Modern React stack, strong design culture, no on-call.",
    responsibilities: [
      "Build accessible, performant interfaces in Next.js",
      "Collaborate with design on a shared component library",
      "Drive Core Web Vitals across the marketing + app surfaces",
    ],
    requirements: ["3+ years React/Next.js", "Strong CSS fundamentals", "Care about accessibility"],
    perks: ["Fully remote", "4-day work week", "Quarterly meetups"],
  },
  {
    slug: "product-manager-keystone",
    title: "Product Manager - Growth",
    company: "Keystone",
    companyInitials: "KS",
    companyAccent: "from-violet-500/30 to-violet-400/10",
    location: "Sydney, NSW",
    workstyle: "On-site",
    employment: "Full-time",
    seniority: "Senior",
    salaryMin: 155000,
    salaryMax: 180000,
    postedAt: "2026-05-07T13:00:00Z",
    applicants: 41,
    category: "Product",
    description:
      "Own activation and retention experiments end-to-end. Partner with eng, design, and lifecycle marketing.",
    responsibilities: [
      "Run a continuous experimentation calendar",
      "Define KPIs and bring weekly insights",
      "Translate growth hypotheses into shipped features",
    ],
    requirements: [
      "4+ years in growth or activation roles",
      "Comfortable with SQL + experimentation tooling",
    ],
    perks: ["Sydney CBD office", "Equity", "Generous PD budget"],
  },
  {
    slug: "junior-fullstack-engineer-yardline",
    title: "Junior Full Stack Engineer",
    company: "Yardline",
    companyInitials: "YL",
    companyAccent: "from-lime-500/30 to-lime-400/10",
    location: "Adelaide, SA",
    workstyle: "Hybrid",
    employment: "Full-time",
    seniority: "Junior",
    salaryMin: 80000,
    salaryMax: 95000,
    postedAt: "2026-05-06T09:00:00Z",
    applicants: 64,
    category: "Engineering",
    description:
      "Join a small, supportive engineering team building tools for the construction industry. Real mentorship and a clear growth path.",
    responsibilities: [
      "Ship features across our Next.js + Express stack",
      "Pair often with senior engineers",
      "Write tests for everything you ship",
    ],
    requirements: [
      "Comfortable in JS/TS",
      "Built something end-to-end (course / hobby / internship)",
    ],
    perks: ["Hybrid Adelaide", "Structured mentorship", "Conference budget"],
  },
  {
    slug: "contract-react-native-developer-tide",
    title: "React Native Developer (Contract)",
    company: "Tide Mobile",
    companyInitials: "TM",
    companyAccent: "from-sky-500/30 to-sky-400/10",
    location: "Remote (AU)",
    workstyle: "Remote",
    employment: "Contract",
    seniority: "Senior",
    salaryMin: 900,
    salaryMax: 1100,
    postedAt: "2026-05-09T20:00:00Z",
    applicants: 9,
    category: "Engineering",
    description:
      "6-month contract building the next version of our trip-planning app. Existing codebase, strong tests, good docs.",
    responsibilities: [
      "Ship features across iOS + Android with shared RN code",
      "Profile and improve startup performance",
    ],
    requirements: ["3+ years of React Native in production", "Comfortable with native modules"],
    perks: ["Day-rate contract", "Async-first team"],
  },
  {
    slug: "marketing-lead-summerfield",
    title: "Marketing Lead",
    company: "Summerfield",
    companyInitials: "SF",
    companyAccent: "from-orange-500/30 to-orange-400/10",
    location: "Melbourne, VIC",
    workstyle: "Hybrid",
    employment: "Full-time",
    seniority: "Lead",
    salaryMin: 160000,
    salaryMax: 190000,
    postedAt: "2026-05-04T12:00:00Z",
    applicants: 22,
    category: "Marketing",
    description:
      "Own brand and lifecycle marketing for our DTC cookware brand. Build the team from a base of one.",
    responsibilities: [
      "Set the brand strategy",
      "Run lifecycle and paid social",
      "Own marketing P&L",
    ],
    requirements: ["6+ years in brand/lifecycle DTC", "Strong analytical eye"],
    perks: ["Hybrid Melbourne", "Annual product allowance"],
  },
];

export const applications: Application[] = [
  {
    id: "a-1",
    jobSlug: "senior-fullstack-engineer-nimbus",
    jobTitle: "Senior Full Stack Engineer",
    company: "Nimbus Labs",
    candidate: "Jordan Pereira",
    email: "jordan@example.com",
    appliedAt: "2026-05-10T22:30:00Z",
    status: "interview",
  },
  {
    id: "a-2",
    jobSlug: "frontend-engineer-loop",
    jobTitle: "Frontend Engineer",
    company: "Loopline",
    candidate: "Anya Olsen",
    email: "anya@example.com",
    appliedAt: "2026-05-10T18:00:00Z",
    status: "reviewing",
  },
  {
    id: "a-3",
    jobSlug: "data-engineer-pivotal",
    jobTitle: "Data Engineer",
    company: "Pivotal Health",
    candidate: "Sasha Hill",
    email: "sasha@example.com",
    appliedAt: "2026-05-09T11:15:00Z",
    status: "offer",
  },
  {
    id: "a-4",
    jobSlug: "product-designer-rivermark",
    jobTitle: "Senior Product Designer",
    company: "Rivermark",
    candidate: "Mateo Diaz",
    email: "mateo@example.com",
    appliedAt: "2026-05-09T08:42:00Z",
    status: "new",
  },
  {
    id: "a-5",
    jobSlug: "junior-fullstack-engineer-yardline",
    jobTitle: "Junior Full Stack Engineer",
    company: "Yardline",
    candidate: "Priya Singh",
    email: "priya@example.com",
    appliedAt: "2026-05-08T16:10:00Z",
    status: "rejected",
  },
];

export const employerSummary = {
  company: "Nimbus Labs",
  activePostings: 3,
  totalApplicants: 73,
  interviewsThisWeek: 5,
  hiresThisQuarter: 4,
};

export function getJobBySlug(slug: string) {
  return jobs.find((j) => j.slug === slug);
}

export const categories = [
  "Engineering",
  "Design",
  "Product",
  "Data",
  "Marketing",
  "Ops",
] as const;
