import type { Project, Task, DiaryEntry, Resource } from "./types";

export const projects: Project[] = [
  {
    id: "northline-m9",
    name: "Northline M9 Upgrade",
    client: "Transport Infrastructure NSW",
    location: "Western Sydney, NSW",
    discipline: "Civil",
    status: "in-progress",
    progress: 62,
    startDate: "2025-02-10",
    endDate: "2027-08-30",
    crew: 184,
    contractValue: 420000000,
  },
  {
    id: "harbour-rail-junction",
    name: "Harbour Rail Junction",
    client: "Metroworks JV",
    location: "Brisbane, QLD",
    discipline: "Rail",
    status: "in-progress",
    progress: 38,
    startDate: "2025-06-01",
    endDate: "2028-04-12",
    crew: 92,
    contractValue: 215000000,
  },
  {
    id: "kingsbridge-precinct",
    name: "Kingsbridge Precinct",
    client: "Civic Holdings",
    location: "Melbourne, VIC",
    discipline: "Buildings",
    status: "in-progress",
    progress: 71,
    startDate: "2024-03-20",
    endDate: "2026-12-15",
    crew: 146,
    contractValue: 312000000,
  },
  {
    id: "morwell-substation",
    name: "Morwell Substation Renewal",
    client: "Powergrid Holdings",
    location: "Morwell, VIC",
    discipline: "Energy",
    status: "on-hold",
    progress: 24,
    startDate: "2025-11-01",
    endDate: "2027-02-28",
    crew: 28,
    contractValue: 64000000,
  },
  {
    id: "redcliff-treatment",
    name: "Redcliff Water Treatment",
    client: "Waterworks Authority",
    location: "Redcliff, QLD",
    discipline: "Water",
    status: "in-progress",
    progress: 49,
    startDate: "2025-01-15",
    endDate: "2026-10-30",
    crew: 64,
    contractValue: 118000000,
  },
  {
    id: "stonepoint-tunnel",
    name: "Stonepoint Tunnel Stage 2",
    client: "Tunnel Alliance Partners",
    location: "Hobart, TAS",
    discipline: "Tunnelling",
    status: "planning",
    progress: 8,
    startDate: "2026-07-01",
    endDate: "2029-06-30",
    crew: 12,
    contractValue: 560000000,
  },
];

export const tasks: Task[] = [
  {
    id: "t-1001",
    projectId: "northline-m9",
    title: "Concrete pour - abutment 4",
    zone: "Zone A - Bridgeworks",
    owner: "Liam C.",
    crew: "Crew Alpha",
    start: "2026-05-12",
    end: "2026-05-13",
    status: "in-progress",
    notes: "12m³ scheduled. Pump primed.",
  },
  {
    id: "t-1002",
    projectId: "northline-m9",
    title: "Reinforcement install - pier 3",
    zone: "Zone A - Bridgeworks",
    owner: "Priya S.",
    crew: "Crew Bravo",
    start: "2026-05-14",
    end: "2026-05-15",
    status: "planned",
  },
  {
    id: "t-1003",
    projectId: "northline-m9",
    title: "Survey set-out - drainage chainage 4+200",
    zone: "Zone C - Drainage",
    owner: "Mateo D.",
    crew: "Survey",
    start: "2026-05-12",
    end: "2026-05-12",
    status: "complete",
  },
  {
    id: "t-1004",
    projectId: "northline-m9",
    title: "Asphalt overlay - west bound L2",
    zone: "Zone D - Pavements",
    owner: "Nora B.",
    crew: "Crew Gamma",
    start: "2026-05-15",
    end: "2026-05-17",
    status: "planned",
    blocked: true,
    notes: "Pending materials delivery.",
  },
  {
    id: "t-1005",
    projectId: "northline-m9",
    title: "Traffic management plan - overnight closure",
    zone: "Zone E - TMP",
    owner: "Sasha H.",
    crew: "TMP",
    start: "2026-05-16",
    end: "2026-05-16",
    status: "planned",
  },
  {
    id: "t-1006",
    projectId: "northline-m9",
    title: "Geotech testing - borehole BH-12",
    zone: "Zone F - Geotech",
    owner: "Eli M.",
    crew: "Subcontractor",
    start: "2026-05-13",
    end: "2026-05-13",
    status: "delayed",
    notes: "Rig delay - 24h knock-on.",
  },
  {
    id: "t-1007",
    projectId: "harbour-rail-junction",
    title: "Track ballast - section 4",
    zone: "Track Zone",
    owner: "Ren K.",
    crew: "Crew Delta",
    start: "2026-05-13",
    end: "2026-05-14",
    status: "in-progress",
  },
  {
    id: "t-1008",
    projectId: "kingsbridge-precinct",
    title: "Façade install - level 8 west",
    zone: "Tower A",
    owner: "Hana O.",
    crew: "Crew Echo",
    start: "2026-05-13",
    end: "2026-05-19",
    status: "in-progress",
  },
];

export const diaryEntries: DiaryEntry[] = [
  {
    id: "d-301",
    projectId: "northline-m9",
    projectName: "Northline M9 Upgrade",
    date: "2026-05-11",
    author: "Liam C.",
    weather: "Clear, 19°C",
    shift: "Day",
    hoursWorked: 10.5,
    crewOnSite: 64,
    plantOnSite: 18,
    summary:
      "Pour of abutment 4 completed early. Reinforcement crews mobilised to pier 3 in afternoon. No safety incidents.",
    flags: ["productive"],
  },
  {
    id: "d-302",
    projectId: "kingsbridge-precinct",
    projectName: "Kingsbridge Precinct",
    date: "2026-05-11",
    author: "Hana O.",
    weather: "Overcast, 14°C",
    shift: "Day",
    hoursWorked: 9,
    crewOnSite: 86,
    plantOnSite: 6,
    summary:
      "Façade install at L8 west progressed two bays. Crane B taken offline for scheduled service.",
    flags: ["maintenance"],
  },
  {
    id: "d-303",
    projectId: "harbour-rail-junction",
    projectName: "Harbour Rail Junction",
    date: "2026-05-10",
    author: "Ren K.",
    weather: "Showers, 18°C",
    shift: "Night",
    hoursWorked: 8,
    crewOnSite: 22,
    plantOnSite: 4,
    summary:
      "Possession executed without delay. Ballast packed across section 4. Sleepers staged for tomorrow.",
    flags: ["possession"],
  },
  {
    id: "d-304",
    projectId: "northline-m9",
    projectName: "Northline M9 Upgrade",
    date: "2026-05-10",
    author: "Eli M.",
    weather: "Clear, 21°C",
    shift: "Day",
    hoursWorked: 10,
    crewOnSite: 60,
    plantOnSite: 20,
    summary:
      "Geotech rig delayed by mobilisation issue - schedule slip of 24h on BH-12. Communicated to PM.",
    flags: ["delay"],
  },
  {
    id: "d-305",
    projectId: "redcliff-treatment",
    projectName: "Redcliff Water Treatment",
    date: "2026-05-10",
    author: "Indra R.",
    weather: "Hot, 31°C",
    shift: "Day",
    hoursWorked: 9,
    crewOnSite: 36,
    plantOnSite: 8,
    summary:
      "Membrane installation across bay 3 completed. Heat policy active - additional water stations rotated.",
    flags: ["heat policy"],
  },
];

export const resources: Resource[] = [
  { id: "r-1", type: "plant", name: "Crawler crane CC-04", utilisation: 86, status: "allocated" },
  { id: "r-2", type: "plant", name: "Excavator EX-12", utilisation: 91, status: "allocated" },
  { id: "r-3", type: "plant", name: "Concrete pump CP-07", utilisation: 64, status: "allocated" },
  { id: "r-4", type: "plant", name: "Tower crane TC-02", utilisation: 0, status: "maintenance" },
  { id: "r-5", type: "labour", name: "Crew Alpha (12)", utilisation: 95, status: "allocated" },
  { id: "r-6", type: "labour", name: "Crew Bravo (10)", utilisation: 78, status: "allocated" },
  { id: "r-7", type: "labour", name: "Crew Gamma (14)", utilisation: 0, status: "idle" },
  { id: "r-8", type: "material", name: "Reinforcement bar (32mm)", utilisation: 72, status: "allocated" },
];

export const portfolioSummary = {
  activeProjects: 5,
  crewToday: 366,
  openIssues: 7,
  onTrackPct: 78,
};

export function getProjectById(id: string) {
  return projects.find((p) => p.id === id);
}

export function tasksForProject(id: string) {
  return tasks.filter((t) => t.projectId === id);
}
